const mockMovie = {
  video: false,
  vote_average: 7.7,
  overview:
    "Washed-up MMA fighter Cole Young, unaware of his heritage, and hunted by Emperor Shang Tsung's best warrior, Sub-Zero, seeks out and trains with Earth's greatest champions as he prepares to stand against the enemies of Outworld in a high stakes battle for the universe.",
  release_date: '2021-04-07',
  title: 'Mortal Kombat',
  adult: false,
  backdrop_path: '/9yBVqNruk6Ykrwc32qrK2TIE5xw.jpg',
  id: 460465,
  genre_ids: [28, 14, 12],
  original_language: 'en',
  original_title: 'Mortal Kombat',
  poster_path: '/xGuOF1T3WmPsAcQEQJfnG7Ud9f8.jpg',
  vote_count: 2335,
  popularity: 5358.559,
  media_type: 'movie',
};

const mockTrendingResults = [
  {
    video: false,
    vote_average: 7.7,
    overview:
      "Washed-up MMA fighter Cole Young, unaware of his heritage, and hunted by Emperor Shang Tsung's best warrior, Sub-Zero, seeks out and trains with Earth's greatest champions as he prepares to stand against the enemies of Outworld in a high stakes battle for the universe.",
    release_date: '2021-04-07',
    title: 'Mortal Kombat',
    adult: false,
    backdrop_path: '/9yBVqNruk6Ykrwc32qrK2TIE5xw.jpg',
    id: 460465,
    genre_ids: [28, 14, 12],
    original_language: 'en',
    original_title: 'Mortal Kombat',
    poster_path: '/xGuOF1T3WmPsAcQEQJfnG7Ud9f8.jpg',
    vote_count: 2335,
    popularity: 5358.559,
    media_type: 'movie',
  },
  {
    adult: false,
    backdrop_path: '/fPGeS6jgdLovQAKunNHX8l0avCy.jpg',
    genre_ids: [28, 12, 53, 10752],
    original_language: 'en',
    original_title: "Tom Clancy's Without Remorse",
    poster_path: '/rEm96ib0sPiZBADNKBHKBv5bve9.jpg',
    vote_count: 757,
    id: 567189,
    vote_average: 7.3,
    video: false,
    overview:
      'An elite Navy SEAL uncovers an international conspiracy while seeking justice for the murder of his pregnant wife.',
    release_date: '2021-04-29',
    title: "Tom Clancy's Without Remorse",
    popularity: 8361.714,
    media_type: 'movie',
  },
  {
    original_language: 'en',
    original_title: 'The Mitchells vs. The Machines',
    poster_path: '/mI2Di7HmskQQ34kz0iau6J1vr70.jpg',
    video: false,
    vote_average: 8.1,
    overview:
      "A quirky, dysfunctional family's road trip is upended when they find themselves in the middle of the robot apocalypse and suddenly become humanity's unlikeliest last hope.",
    release_date: '2021-04-22',
    vote_count: 504,
    adult: false,
    backdrop_path: '/egxe0rPverBETHzV6COXFGL4edC.jpg',
    id: 501929,
    genre_ids: [16, 12, 35, 10751, 878],
    title: 'The Mitchells vs. The Machines',
    popularity: 240.34,
    media_type: 'movie',
  },
];

const mockSearchResults = [
  {
    overview:
      'In a time when monsters walk the Earth, humanity’s fight for its future sets Godzilla and Kong on a collision course that will see the two most powerful forces of nature on the planet collide in a spectacular battle for the ages.',
    release_date: '2021-03-24',
    title: 'Godzilla vs. Kong',
    adult: false,
    backdrop_path: '/inJjDhCjfhh3RtrJWBmmDqeuSYC.jpg',
    genre_ids: [878, 28, 18],
    id: 399566,
    original_language: 'en',
    original_title: 'Godzilla vs. Kong',
    poster_path: '/pgqgaUx1cJb5oZQQ5v0tNARCeBp.jpg',
    vote_count: 5403,
    video: false,
    vote_average: 8.1,
    popularity: 3621.502,
    media_type: 'movie',
  },
  {
    overview:
      'Hutch Mansell, a suburban dad, overlooked husband, nothing neighbor — a "nobody." When two thieves break into his home one night, Hutch\'s unknown long-simmering rage is ignited and propels him on a brutal path that will uncover dark secrets he fought to leave behind.',
    release_date: '2021-03-26',
    title: 'Nobody',
    adult: false,
    backdrop_path: '/6zbKgwgaaCyyBXE4Sun4oWQfQmi.jpg',
    genre_ids: [28, 53, 80],
    id: 615457,
    original_language: 'en',
    original_title: 'Nobody',
    poster_path: '/oBgWY00bEFeZ9N25wWVyuQddbAo.jpg',
    vote_count: 1346,
    video: false,
    vote_average: 8.4,
    popularity: 2861.481,
    media_type: 'movie',
  },
];

module.exports = {
  mockMovie,
  mockTrendingResults,
  mockSearchResults,
};
